export const CHANGE_CATEGORY="CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS="GGET_CATEGORIES_SUCCESS";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const ADD_TO_CARD="ADD_TO_CARD";
export const REMOVE_FROM_CARD="REMOVE_FROM_CARD";
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"

